version: '3.9'
services:
  win:
    image: electronuserland/builder:wine
    volumes:
      - ~/.cache/electron:/root/.cache/electron
      - ~/.cache/electron-builder:/root/.cache/electron-builder
      - ./:/project
    environment:
      - ELECTRON_CACHE="/root/.cache/electron"
      - ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder"